### ISSUE TITLE
Same for Brotli

### ISSUE THREAD

**Issue by DanielRuf** [plan2net/webp#11]
It would be great to also have a similar Brotli extension for text files (css, js, svg and a few more).

**Comment by wazum** [comment]
Thanks for your request, but this extension is about webp only.

**Comment by DanielRuf** [comment]
> Thanks for your request, but this extension is about webp only.

Sure. But do you plan to create another one for Brotli?

**Comment by wazum** [comment]
Currently not, no, none of our customers had a need for that yet, so the motivation is limited right now to spend time on technologies for which we have no practical use.
But there may come the time for it.

**Comment by DanielRuf** [comment]
> for which we have no practical use

Well, I take WPO very serious and this is important for mobile devices (3G) too ;-)

**Comment by masi** [comment]
As long as there is no extension that does static compression you can always use dynamic compression in the websever as it has been done for years with gzip and deflate.

And maybe an extension called webp isn't the right place for such a request ;)

BTW, except for webp one could also ask for image optimization of other formats like it's done with imagemin :)

**Comment by DanielRuf** [comment]
> dynamic compression

This is not good as this adds additional load onto the server and increases the TTFB - delivering static precompiled assets is faster and recommended.

https://css-tricks.com/brotli-static-compression/

> And maybe an extension called webp isn't the right place for such a request ;)

Sure. but where should I request another extension with the same structure and behavior but different compressor and output? ;-)

So it makes sense to ask here.
And both could be bundled as WPO extension.

> BTW, except for webp one could also ask for image optimization of other formats like it's done with imagemin :)

See the libvips / sharp discussion.
