### ISSUE TITLE
wrong extraction of extConf value

### ISSUE THREAD

**Issue by akiessling** [plan2net/webp#13]
https://github.com/plan2net/webp/blob/2f2574bcb7af7f0d3b3801e79755e9fe7d62a4ee/Classes/Processing/Webp.php#L149

The method getExtensionConfiguration does not return the value from a given $key but the $key itself. Thus `$convertAllImages = (bool)$this->getExtensionConfiguration('convert_all_images');` is always true and all images in the fileadmin will get a correspondig webp image although the option is not enabled.

**Comment by wazum** [comment]
Thanks, nice catch

**Comment by akiessling** [comment]
The reading out of the configuration should still be improved, because if a given key is not found in the configuration array, the whole array will be returned. In that case, probably null should be returned.

**Comment by wazum** [comment]
Fixed in `1.1.1`

**Comment by akiessling** [comment]
Nice! Thanks for the fix!
