### ISSUE TITLE
Error or action log?

### ISSUE THREAD

**Issue by Norcoen** [plan2net/webp#15]
I installed EXT:webp on an installation with v8 and v9, ImageMagick is working (I can convert to webp in the command line) and TYPO3 is configured to use IM

So far nothing is happening for me, I don't see any *.webp being generated.

How can I tell what the extension is doing, what going wrong or maybe it is not running at all?

**Comment by wazum** [comment]
No, there's currently no logging. You can use a debugger, creation of files happens here: `\Plan2net\Webp\Service\Image\Webp::process`

Did you follow the Installation instructions?

1. Install and activate the extension in the Extension manager
2. Flush TYPO3 and PHP Cache
3. Clear the processed files in the Install Tool or Maintenance module

**Comment by Norcoen** [comment]
I had to install some webp libraries to make ImageMagick work with webp on Ubuntu 16.04, otherwise it just silently failed.
I had support for webp in graphicsmagick, but the extension did not like it, I guess

Would be great to have some sort of self-check mechanism in the extension

**Comment by wazum** [comment]
The documentation already contains advice to check ImageMagick or GraphicsMagick possibilities. There's currently no way (at least that I know) to run a script when an extension is installed/activated.

**Comment by masi** [comment]
The extension could provide a section for the "reports" module.

**Comment by Norcoen** [comment]
> The documentation already contains advice to check ImageMagick or GraphicsMagick possibilities. There's currently no way (at least that I know) to run a script when an extension is installed/activated.

Just for the reference:

```sh
gm version | grep WebP
  WebP
```

```sh
$ convert version | grep webp
# [nothing]
```
wrong command, guess you missed a - (minus) there:

```sh
$ convert -version | grep webp
# [still nothing]

#but:
$ convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```

no webp is listed here, but

```sh
$ convert -list delegate | grep webp
        png<= webp      "cwebp" -quiet -q %Q "%i" -o "%o"
       webp =>          "dwebp" -pam "%i" -o "%o"
```

It's there and working with the extension as intended now, but the test you proposed failed.

I think a test similar to the tests for png, jpg, gif, etc. in the install tool where you can actually render a picture and compare it to a reference image, would be a great thing.

**Comment by wazum** [comment]
Tested again with ImageMagick 7.0.8-23
```convert version | grep webp
Delegates (built-in): bzlib freetype jng jp2 jpeg lcms ltdl lzma png tiff webp xml zlib``` 
works … so it might depend on the version or platform you're using.
I'll add a hint to the documentation.

Feel free to make a pull request for such a test feature. I rely on the system administrator to be able to check webp support before using the software for now.
