### ISSUE TITLE
Not all pictures get converted to webp (Case Sensitive!)

### ISSUE THREAD

**Issue by M4rt1n17** [plan2net/webp#18]
All images with the ending "jpg" gets converted to webp
No images with the ending "JPG" gets converted to webp!

I THINK "Jpg", "JPg", "JPG", "jPG", "jpG", "JpG" and "jPg" will be ignored.
Same at png.

![nur jpg aber keine JPG](https://user-images.githubusercontent.com/17692860/57715479-28405000-7677-11e9-800d-2fd475db19de.PNG)

I would recommend implementing this: [LINK](https://im-coder.com/regex-gross-kleinschreibung-ignorieren.html) to make RegEx ignoringing case-sensitive.

Also (png|jpg|jpeg) could get shorten down to (png|jpe?g) but this one is just cosmetic

**Comment by wazum** [comment]
You can do whatever you want in your rewrite rules (the extension has nothing to do with that).

The webp files are generated for alle file extensions you mentioned.
https://github.com/plan2net/webp/blob/master/Classes/Processing/Webp.php#L142

**Comment by M4rt1n17** [comment]
I know, the second part was just for having shorter RegEx.

But how can I (re)start the convertion process? NONE of the Files with "JPG" has been converted, but nearly all with "jpg" how do you explain that?
So for me not all Images has been converted

**Comment by M4rt1n17** [comment]
Just tested it again.

Tested with Pic which does not get processed (pic still in /fileadmin/user_upload/)
Uploaded 35 HR Images (half JPG half jpg)

All Images get included with full Link to source and once processed.
All pics in processed are webp (and jpg after being processed)
All JPG pics in user_upload are delivered as jpg (webp not even generated!)
All jpg pics in user_upload are delivered as webp.

See Screenshot:
![JPG = no webp](https://user-images.githubusercontent.com/17692860/57726870-626a1b80-7690-11e9-9a07-d00e1c2c4545.PNG)

Have done this from an anonym Tab with cach flushed in Chrome.
Also I checked my htaccess and the other configs. If there would be any error it would not work at all but its just not working at Files with JPG (which gets included directly without processing)

I dont think this Issue is invalid

**Comment by M4rt1n17** [comment]
Anoster thing I noticed:

All my JPG Files are all bigger then 1,2 MB
All my jpg Files are all smaller then 800kb

Is there maybe a limitation of PHP, Ressoureces, Times which just applys to the JPG Files but not because they are JPG but because they are much more bigger (about 6000x4000 px)?

Noticed there is this Error in my Log:
`(70007)The timeout specified has expired: AH01075: Error dispatching request to : (polling)`
Maybe its related to this maybe not.

Also all of my Images are "responsive Images" wich 4 lower resolutions.
So for all this big pictures (which itself also have to be converted to webp, also 4 smaller editions of it also have to be converted to webp. Could this also be the problem?

Will debug this a bit and report back

**Comment by MartinH0** [comment]
Any news on this?
Why are images ending with "JPG" not getting converted, but if they end with "jpg" they do?

Cant the Extension handle JPG Files but jpg?
The only difference is the file extension is wrote uppercase.

Why is convertion not getting triggered for the uppercase ones?
