### ISSUE TITLE
Different command parameters for JPG and PNG

### ISSUE THREAD

**Issue by koehnlein** [plan2net/webp#21]
First of all, thanks for your work and your extension.

I did some tests with the parameters to find out, what's the best command for my images on my server. Because of my short experiences, I ask myself, if it would be a good feature to have different command parameters for JPG and PNG file types. I my case, I get the best result for JPG files with `lossless=true` and for PNG files with `lossless=false`. Maybe defining different command parameters for different JPGs and PNGs could be a benefit for other users, too.

**Comment by wazum** [comment]
Done
