### ISSUE TITLE
UPPERCASE file extensions are not getting converted

### ISSUE THREAD

**Issue by MartinH0** [plan2net/webp#23]
Reffering to https://github.com/plan2net/webp/issues/18 as I do not get any answer there.

if you do have two images

1. image1.jpg
2. image2.JPG

the extension will NOT convert the one with uppercase fileextension!
Means you end up having these files:

1. image1.jpg
2. image1.jpg.webp
3. image2.JPG

Proof:
![57715479-28405000-7677-11e9-800d-2fd475db19de](https://user-images.githubusercontent.com/17692860/70467216-1582e200-1ac5-11ea-94e2-4bb0f33db91d.png)

Just the two first Images are getting converted.

And no this Issue is not "invalid" as the other is marked as invalid, even if I had the wrong idea to fix this. Yes its not related to the htaccess.

Hope this helps to fix this issue.

Anyway this issue does just happen on unprocessed pictures as all images which are getting processed by TYPO3 are getting new filenames which are always lowercase.
So this just applys to pictures which you gonna upload with uppercase fileextensions

**Comment by wazum** [comment]
As said before I can't reproduce _your_ problem.
But feel free to provide more information (step through the class with a debugger) or even do a pull request. This is open source, we appreciate your help to fix issues. Thanks.
I leave this ticket open for a while, so you can report back.

**Comment by MartinH0** [comment]
I dont know why either, but somehow these Images (they are very big btw 6000x4000, 24MP 3:2) are not getting converted to webp, also they are 100% optimized, what makes them so small, but indeed they are very big.

The smaller ones (4000x3000 12MP 4:3) are getting converted but also not all.
Maybe the convertion is hitting some timeouts or something like this?
