### ISSUE TITLE
[Question] how to use other Image-manipulation Libs (VIPS)

### ISSUE THREAD

**Issue by MartinH0** [plan2net/webp#24]
I just installed libvips on my Server and tryed to use this Extension (https://github.com/christophlehmann/vips/) to generate the webp files as VIPS is much faster then IM or GM or any other Image-Manipulation libs. But unfortunately it seems not to work properly.

But as aleady asked here https://github.com/plan2net/webp/issues/10#issuecomment-489101083 I dont know how to use other libs/parameters, is there somewhere a field I can paste the path to my vips libs?

I would love to be able to configure the extension in a way to use VIPS to convert to webp as it is much faster ans consumes a lot less ressources (memory/CPU/time).
I also hope this helps me to bypass the problem of (maybe) hitting some timeouts etc at very large Images. (https://github.com/plan2net/webp/issues/23#issuecomment-568773168)

When regenerating the webp images for a dynamic galery (60 pictures about 4000x3000) it takes about 20min at a 4-core 8GB RAM VPS. I'm atm using ImageMagick with webp.

> **#** convert -version
> ```
> Version: ImageMagick 7.0.8-27 Q16 x86_64 2019-02-10 https://imagemagick.org
> Copyright: © 1999-2019 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC HDRI OpenMP
> Delegates (built-in): bzlib djvu fftw fontconfig freetype gvc jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff webp wmf x xml zlib
> ```

So the question is: how can I configure the extension to use libvips, or is there no way?

**Comment by wazum** [comment]
Simply set the command line to convert in the extension configuration, it's described in the [README](https://github.com/plan2net/webp#extension-manager-configuration).
Example:
`image/jpeg::/path/to/vips webpsave %s %s`

**Comment by wazum** [comment]
Quick follow-up to my earlier reply: in addition to the CLI route via `ExternalConverter`, v14.4.0 added a native `VipsConverter` backend that calls libvips in-process via jcupitt/vips + PHP FFI. It's 2–3× faster than the CLI route at equivalent quality and preserves animated GIFs automatically. Pick *libvips (native)* from the converter dropdown.

Release notes: https://github.com/plan2net/webp/releases/tag/14.4.0
