### ISSUE TITLE
Unable to Install from ZIP

### ISSUE THREAD

**Issue by superscotty19** [plan2net/webp#27]
Hi,

TER only has v 1.0.
I want 2.2!
But every time I try to import .zip into Extension Manager, I get a red warning box saying, "Extension webp-2.2.2 is not available".
I have tried downloading/installing just about every .zip/version

Help?
-Scott.

**Comment by wazum** [comment]
I'll upload a new version to TER in the next days, hth @superscotty19 
(to be honest, I have no experience with non-composer installations anymore)

**Comment by wazum** [comment]
Release the latest version on TER,  hth @superscotty19
