### ISSUE TITLE
Problem with external converter

### ISSUE THREAD

**Issue by gregordonsky** [plan2net/webp#28]
I have a problem using cwep for converting images.

https://github.com/plan2net/webp/blob/b67fb657a011ba2b0133920977e9b75f43896e69/Classes/Converter/ExternalConverter.php#L36
This line check if a file is executable, but PHP's open_basedir restriction causes failure when cwebp is available, but not openable.
So my cweb binary is executable but the check fails.

This is the error:
`Core: Error handler (FE): PHP Warning: is_executable(): open_basedir restriction in effect. File(/usr/bin/cwebp) is not within the allowed path(s)`

To check if a file is executable i propose this solution:
```php
$command = sprintf('test -x %s', $binary);
$output = NULL;
$returnValue = NULL;
CommandUtility::exec($command, $output, $returnValue);
if ($returnValue !== 0) {
    throw new InvalidArgumentException(sprintf('Binary "%s" is not executable!', $binary));
}
```
I don't know if this solution works correctly also in Windows.
I think that the correct way of checking if the command is valid is to use:
```php
CommandUtility::checkCommand($binary) !== true
```
instead of is_executable() .
Unfortunatly this method does not resolve the problem above.

**Comment by wazum** [comment]
@gregordonsky `CommandUtility::checkCommand` uses `is_executable` too.

I don't think I want to open up a way in my extension to call commands that are deliberately restricted.
If your server administrator restricts executions from PHP to certain directories there's surely a reason for that.

**Comment by gregordonsky** [comment]
That's a point of view...
The command itself is executable from php, so the execution is not restricted.
I don't know why `is_executable()` function return a wrong result.
`open_basedir` is used for limit the files that can be accessed by PHP, but not the command execution.

I have a warning in typo3's Environment regarding the `open_basedir` directive but this not prevent the use of `/usr/bin/convert` because in this case `is_executable()` is not used in `CommandUtility::imageMagickCommand`.
So I think that the implementation of `CommandUtility::checkCommand` is wrong too, but it is more reliable than using directly `is_executable` because it take into consideration other OS.
Obviously from my point of view  :simple_smile:

**Comment by wazum** [comment]
I will discuss the issue with colleagues next week
