### ISSUE TITLE
Convert images of different folder

### ISSUE THREAD

**Issue by vruescas** [plan2net/webp#3]
Hello,

i have a question, i try to use the webp plugin, but my project have a lot of images out of _processed_ folder. You know how i can convert this images?

My try:
`<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTP_ACCEPT} image/webp
    RewriteCond %{DOCUMENT_ROOT}/$1.webp -f
    RewriteRule ^(fileadmin.+)\.(jpe?g|png)$ $1.webp [T=image/webp,E=accept:1]
</IfModule>

<IfModule mod_headers.c>
    Header append Vary Accept env=REDIRECT_accept
</IfModule>

AddType image/webp .webp`

**Comment by wazum** [comment]
This extension handles only processed (resized, cropped) images.

You would have to script this yourself to batch-convert all (or other) images.
Take a look at the methods in
https://github.com/plan2net/webp/blob/master/Classes/Service/Image/Webp.php
where I'm using imageMagickExec.

hth

**Comment by M4rt1n17** [comment]
I would also be interested in a global WebP handeling from this extension.
I think a lot of pictured gets included without cropping/resizing. Like Logos etc.
Why should someone crop them/resize them just to get them handeled as webP..?

In your read me you have written from mod_pagespeed as alternative, but Mod Pagespeed is for every image, not just processed etc. So in this example I see mod_pagespeed as superior as it converts ALL the Images which are png/jpg.

**Comment by M4rt1n17** [comment]
I already tested the v1.1.0 and It seems not to generate any .webp for me.
Is there a button to trigger the "convert all images" to WebP action or how does that get initiated?

I checked /fileadmin/user_upload/, /fileadmin/_processed_/ and /fileadmin/_temp_/ but no .webp file have been in there.
Does the generated webp gets generated somewhere else?

Also I have copied the standard .htaccess config (without the "other-storage" line)
Is this basic config working for you?

Here my complete .htaccess:

```
# ------------------------------------------------------------------------------
# |                          ### WebP Support ###                              |
# ------------------------------------------------------------------------------
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{HTTP_ACCEPT} image/webp
    RewriteCond %{DOCUMENT_ROOT}/$1.$2.webp -f
    RewriteRule ^(fileadmin/.+)\.(png|jpg|jpeg)$ $1.$2.webp [T=image/webp,E=accept:1]
</IfModule>

<IfModule mod_headers.c>
    Header append Vary Accept env=REDIRECT_accept
</IfModule>
```
This part is already included (more down in the htaccess) in the standard Typo3 .htaccess:

`AddType image/webp .webp`

But I also tried it with adding it right behind the other config. Did not change anything.

**Comment by wazum** [comment]
@M4rt1n17  if you had installed the extension before, you'll have to update (just save once) the extension configuration via the Extension Manager. The Webp copy is always stored in the same folder as the original file.

**Comment by wazum** [comment]
@M4rt1n17 and I guess you'll have to clear your processed files (via Install tool or manually) or test with a new image uploaded and included on a page

**Comment by wazum** [comment]
@M4rt1n17 I just double-checked with a fresh install and it works as advertised, hope you find the problem, would be curious to know

**Comment by M4rt1n17** [comment]
> @M4rt1n17 I just double-checked with a fresh install and it works as advertised, hope you find the problem, would be curious to know

I'm sorry to say, but I just uploaded a fresh image (jpg) and tested it with the new one.
I also cleaned all processed files a lot times befor and also now, but I never got a .webp from this extension.
Is there maybe one more dependency this extension needs?

I also added (befor) images via webinterface from server and not Typo3, so I have both now: fileswhich are uploaded from Server and files which are uploaded from Typo3 Backend. Problem is: its not working for both..

I think even if there would be a mistake in teh htaccess this would not affect the convertion to webp??
But this extension does not convert any Image to webp for me.
This installation has access to 4GB Ram and 4 Cores a 3,2Ghz. This should be enough.

Log in Typo3 and at the Server is empty, ... well not empty, normal log files but not even a warning, and no errors

**Comment by wazum** [comment]
@M4rt1n17 So it did not work before your first comment on this thread either?

And yes, sure, there's another dependency: your version of ImageMagick oder GraphicsMagick on the server needs to support Webp (I'll update the README if that's not clear enough).

You can test it with (example for GraphicsMagick, see ImageMagick documentation if you use that):
`/usr/bin/gm convert +profile '*' -quality 95 -define webp:lossless=false 'myimage.jpg[0]' 'myimage.jpg.webp'`

**Comment by M4rt1n17** [comment]
No I just checkt it afterwards, but never a webp got created in this Typo3 Installation.

You are right, my Version of ImageMagick does not support webp...
I'm using the latest ImageMagick Version for Debian 9.

I just brew my own ImageMagick version, (version 7 which supports WebP) and also installed "webp"
Now it works... at least all the webp Pics get generated.

**Comment by wazum** [comment]
Thanks, so I close this issue as resolved

**Comment by wazum** [comment]
Heads-up for anyone landing here: since v14.1.0 the `webp:process-queue --folder=<path>` command converts images in arbitrary folders without needing them to go through TYPO3's FAL processing pipeline. Useful for `typo3temp/`, custom media folders, or any directory under the public web root.
