### ISSUE TITLE
*.jpeg files are not converted

### ISSUE THREAD

**Issue by markustobler** [plan2net/webp#31]
I was wondering why some files are not converted to webp and I found out that all this files are *.jpeg and not *.jpg. Not sure if this is only my problem?

**Comment by wazum** [comment]
The extension checks for the mime type, so the file extension could be anything.
Converted files are only kept if they are smaller than the original, so try to convert an example file with the exact arguments you configured manually and compare the resulting file size.
The second thing could be your rewrite rule. Double check that.

**Comment by wazum** [comment]
No further comment (unfortunately), so I close this issue

**Comment by Inf166** [comment]
I stumbled upon the same problem as @markustobler. I tried adding the jpg to the extension configuration so it would convert them proparly. I am not sure about what you said @wazum - I mean it could be that converting a jpg to webp is not significantly smaller than the original, but in my defense - the converted image should be reduced in size for the different source sets. So I think, the extension should still deliver at least all the smaller variants, if not the original.

[I followed this tutorial](https://www.in2code.de/aktuelles/webp-responsive-images-und-lazy-loading-in-typo3-einbauen/)

**Comment by wazum** [comment]
@Inf166 so you say, you got a jpg (or jpeg) file and when converted by hand the webp is smaller than the original and the extension did not convert this file? It works with other files (where the result is differen)?
Do you see any entries in the database table `tx_webp_failed` where the `file_id` matches the failed file?
