### ISSUE TITLE
Better nginx configuration?

### ISSUE THREAD

**Issue by xperseguers** [plan2net/webp#33]
I had problems with Safari on macOS and iOS using suggested nginx configuration. I switched to the one here: https://centminmod.com/webp/ and it seems to be working (I'm behind Cloudflare btw).

**Comment by omueller** [comment]
Thanks for the link!   and if you want to stick to the original sample from the readme (but it should be also the case for https://centminmod.com/webp/), it seems Safari (latest version 14.0.3 on 20.04.2021, Mac OS Big Sur) doesn't list `image/webp` in its Accept header: 
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

So to make it work with under nginx, we had to modify the map like this: 

```
map $http_accept $webp_suffix {
       default "";
       "~\*\/\*" ".webp";
       "~*webp" ".webp";
}
```

Curl also just uses `Accept: */*`, so it was logically also failing during our initial tests over the console.   Maybe I missed something, but if not, this could also help spare some time for other webp enablers.

**Comment by wazum** [comment]
Updated README, thanks
