### ISSUE TITLE
Support for application/pdf MIME TYPE

### ISSUE THREAD

**Issue by gregordonsky** [plan2net/webp#34]
It should be possible to add application/pdf mime type support?

If i insert an Image Content Element; Pdf extension is supported, but the image it's not converted in webp format.

Adding 'application/pdf' to `const SUPPORTED_MIME_TYPES` seems to do it.... i don't know if there is any drawback applying this change

Thanks for your efforts! :)

**Comment by wazum** [comment]
Fixed in 3.1.0 via extension configuration (new option: mime_types)
