### ISSUE TITLE
Error: maybe missing support for webp?

### ISSUE THREAD

**Issue by ohm-meter** [plan2net/webp#38]
Hi,
I got this error:

> [ERROR] request="076353e424a0d" component="Plan2net.Webp.EventListener.AfterFileProcessing": Failed to convert image to webp: File "/home/dev.at/public/fileadmin/user_upload/dummy/dummy-3.png.webp" was not created: maybe missing support for webp?!

Webp is enabled:

> convert version | grep webp     
> Delegates (built-in): bzlib freetype jng jpeg lcms png tiff webp xml zlib

>  convert -list delegate | grep webp
>         png<= webp      "cwebp' -quiet %Q '%i' -o '%o"
>        webp =>          "dwebp' -pam '%i' -o '%o"

How can I debug this ?
Cheers...

**Comment by wazum** [comment]
@ohm-meter  which converter are you using? Looks like you're using the internal _Magick_ one, but rather should use the _External_ converter configured for `cwebp` (see README)

**Comment by ohm-meter** [comment]
Thanks, 

If i change it to External i got this error:

> component="Plan2net.Webp.EventListener.AfterFileProcessing": Failed to convert image to webp: Command string is invalid, supply 2 string (%s) placeholders!

I think i have to Change the config: 
`For each mime type conversion parameters (for internal adapter) or command + parameters (in sprintf format for external adapter) (see documentation)`

Where do i find this Config ?

**Comment by wazum** [comment]
https://github.com/plan2net/webp#extension-manager-configuration

**Comment by ohm-meter** [comment]
Thanks that helped...
