### ISSUE TITLE
isFileInProcessingFolder issue

### ISSUE THREAD

**Issue by bernd-reindl** [plan2net/webp#40]
In \Plan2net\Webp\EventListener\AfterFileProcessing the file is checked for isFileInProcessingFolder. If not in processing folder (this means the file wasn't changed) the original file is used for processing the webp image. But $processedFileWebp uses the configuration of $processedFile.

So it's possible that multiple database rows with same identifier but different configurations exist. And this leads to problems by ProcessedFileRepository->findByStorageAndIdentifier().

You can solve this by setting a blank configuration if isFileInProcessingFolder() returns false.

```
if (!$this->isFileInProcessingFolder($processedFile)) {
                // In this case the processed file has the wrong storage record attached
                // and the file would not be found in the next steps,
                // so we use the original file then
                $processedFile = $file;
                $configuration = [
                    'width' => null,
                    'height' => null,
                    'minWidth' => null,
                    'minHeight' => null,
                    'maxWidth' => null,
                    'maxHeight' => null,
                    'crop' => null
                ];
            }
```
But this has to be done before $processedFileWebp is created.

I attached the screenshot how to solve it.

![webp1](https://user-images.githubusercontent.com/2369089/96000814-98886d80-0e37-11eb-90a9-444eb341a385.jpg)

My original file is 32x32. So the file isn't changed in both cases and the original file is used. But now there are two equal identifiers. 

![webp3](https://user-images.githubusercontent.com/2369089/96000816-99b99a80-0e37-11eb-9bf2-e15e0ba36eb1.jpg)

![webp2](https://user-images.githubusercontent.com/2369089/96000815-99b99a80-0e37-11eb-98a0-ffdcfc2bc203.jpg)

**Comment by wazum** [comment]
Thanks for the report, will take a look at it tomorrow

**Comment by wazum** [comment]
Fixed in current master, thanks
