### ISSUE TITLE
Hundreds of queries to check for failed attempts really neccesary?

### ISSUE THREAD

**Issue by bernhardberger** [plan2net/webp#42]
https://github.com/plan2net/webp/blob/c094f9fc2e294a68c68c43d3be7caf3e47be2bf1/Classes/Service/Webp.php#L47

Is this check really neccesary? This causes a **butload** of queries.

My scenario:
- I have a site (single page) with about 100 images
- if I include responsive formats multiply that by 4-6
- this site has heavy traffic (about 2000 concurrent fe_users during business hours and probably 1000 hits per minute as the page autoloads when a users opens the browser or just a new tab

Results in:
500 * 1000 = 0.5 mio queries per minute for that check alone.

Can this be optimized? I'm happy to submit a PR if anyone suggest an approach..

**Comment by wazum** [comment]
Merged https://github.com/plan2net/webp/commit/261f861c10926bdd3e49df57b28f80705fdfbab7
Should be a lot faster now, but why would heavy traffic have any impact on this? The images are generated usually once (see https://github.com/plan2net/webp/blob/c094f9fc2e294a68c68c43d3be7caf3e47be2bf1/Classes/EventListener/AfterFileProcessing.php#L63). 
Maybe you can give some insights into your setup, why processing these images would be called all the time?

**Comment by infabo** [comment]
> Maybe you can give some insights into your setup, why processing these images would be called all the time?

Would be interested too

**Comment by infabo** [comment]
> Is this check really neccesary? This causes a butload of queries.

btw, it is **buttload**
