### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by toccamonium-fe** [plan2net/webp#50]
Hi, we are using TYPO3 version 10 and got suddenly this message, any idea what would cause it?

![2021-04-21_10-05-28](https://user-images.githubusercontent.com/55410878/115520225-38f99780-a28a-11eb-8a58-5efa9725f25d.jpg)

Thx

**Comment by wazum** [comment]
@toccamonium-fe  looks like composer has no autoload information for the class, either try to run `composer dump-autoload` to update autoloader information or remove the extension from `typo3conf/ext` and run `composer install` again.

**Comment by wazum** [comment]
No further response, issue closed.
