### ISSUE TITLE
False "is larger than the original" output

### ISSUE THREAD

**Issue by createdwithlove** [plan2net/webp#51]
Just found a strange behaviour with .webp files generated (about 30% smaller than .jpg ones), but the log says:

```
[WARNING] request="4bf03a46d6722" component="Plan2net.Webp.EventListener.AfterFileProcessing": Converted file (/www/htdocs/xxx.de/public/media/_processed_/3/d/csm_image.jpg.webp) is larger than the original (/www/htdocs/xxx.de/public/media/_processed_/3/d/csm_image.jpg)! Will not retry with this configuration!
```

The .jpg.webp files are generated as expected und the filesize is definitely smaller compared to originals.

TYPO3 10.4.17 with EXT:webp 3.1.1 on

**Comment by xerc** [comment]
fyi/ this message was used twice; https://github.com/plan2net/webp/pull/58/commits/7c40184338492e0f7b914b0d71ab95ba2c891546

**Comment by wazum** [comment]
@createdwithlove can't reproduce this, but I updated the error messages (unique and with more information),
please test with the latest version 4.1.2 and open a new issue if the problem occurs again (with more information).
