### ISSUE TITLE
File gets converted but not displayed in frontend

### ISSUE THREAD

**Issue by omni-primus** [plan2net/webp#59]
I've download and installed Version 2.2.2 for my Typo 9.5.14 environment and can't manage to display the webp images in my frontend. I've followed the README file step by step, the images are getting converted into the _processed_ directory and they are accessable if I enter the url into my browser. I adjusted the htaccess file as it is described.
However, for whatever reason the webp images are not getting shown in the frontend, only the normal variants of the images.
I'm pretty clueless on what to do and I can't find a solution to my problem on google.

Browser result:
![image](https://user-images.githubusercontent.com/56962599/149979362-b80caffe-4107-461c-8a33-9b09c82dba78.png)

Files in directory:
![image](https://user-images.githubusercontent.com/56962599/149979613-46869c0a-9dde-49a5-97b0-c26adf24ed11.png)

Typo3 extention settings:
![image](https://user-images.githubusercontent.com/56962599/149978263-8f145cdc-143c-4d47-842b-fa30a759716f.png)

htacccess code:
![image](https://user-images.githubusercontent.com/56962599/149978453-98559b93-410b-488a-bf9e-cf60e36a4a20.png)

I'm not getting an error message or something, it's simply not working for me.

Any idea what the problem might be?

**Comment by wazum** [comment]
@omni-primus where did you add the rules in your `.htaccess` file? As stated in the README, you have to make sure the rules are not overruled by any other existing rule. So the best bet is to add them at the top after the `RewriteEngine On` directive.

**Comment by omni-primus** [comment]
Ah thanks, that fixed it
