### ISSUE TITLE
webp quality is quiet bad

### ISSUE THREAD

**Issue by M4rt1n17** [plan2net/webp#6]
I already set quality to 100% **and** set convertion to lossless but the quality difference is still noticable pretty easy.
After this i converted the same jpg with a [onlinetool](https://image.online-convert.com/convert-to-webp) to webp and the wuality was much better.

The components I'm using are these:

PHP 7.3.1
ImageMagick 7.0.8-25

Is there anything else what I can do to achive webp (smaller pictures) but really good quality?
If you want I can provide a example of what this extension created and what the onlinetool created.

My settings are: -quality 100 -define webp:lossless=true

Original jpg = 280kb
webp ext = 100kb
webp online: 120kb

For me quality is more important then 20kb but I would like to have the highest quality at the best lossless compression :)
Hope you understand. Is there anything what I can do to have higher quality webp?

**Comment by wazum** [comment]
@M4rt1n17 that's no issue of this extension (sorry ;-) ), so I'll close the issue.

My advice: 
try it on the server with different options (you'll find all webp options for ImageMagick at the link given in the documentation), e.g.:

`/usr/bin/gm convert +profile '*' -quality 50 -define webp:lossless=false -define webp:method=6  
 -define webp:auto-filter=true -define webp:partition-limit=1 'myimage.jpg[0]' 'myimage.jpg.webp'`

before setting the final options for the extension
(and don't forget to remove the processed files to regenerate them).

My version of ImageMagick (7.0.8-23) produces really good results even with -quality 50 and lossless=false!

hth
