### ISSUE TITLE
Downloading the original file from the backend

### ISSUE THREAD

**Issue by akiessling** [plan2net/webp#62]
One of my editors asked me, how he could download an original image file in the TYPo3 backend. We configured the convert_all flag and thus whenever he tried to save the image he got the webp version served.
If i remember correctly, i tried this some months ago with Chrome and it downloaded the original jpg. Now it wants to save the webp version and so i assume that it now maybe sends different headers so the rewrite rule kicks in.

I thought about adding a dedicated download button to the file list module. The download attribute seems to work to get the original file. Or maybe the rewrite condition could be modified to skip if a certain parameter is set?

Is there any other / better / easier way for editors to get the original file? 

The system i'm dealing with here is T3 9.5 with and thus version 2.2.2 of the webp extension

**Comment by xerc** [comment]
specifiy one/more folders within
OR add .. in front of the rule-set
```
  RewriteCond %{HTTP_COOKIE} !be_typo_user
```

**Comment by wazum** [comment]
Thanks for answering the question @xerc
