### ISSUE TITLE
Feature Request: Support VHS image viewhelpers

### ISSUE THREAD

**Issue by Ceremony64** [plan2net/webp#65]
On my website, I am using the [im](https://viewhelpers.fluidtypo3.org/fluidtypo3/vhs/5.0.1/Media/Image.html)[age](https://viewhelpers.fluidtypo3.org/fluidtypo3/vhs/5.0.1/Uri/Image.html) viewhelpers provided by the [VHS extension](https://extensions.typo3.org/extension/vhs/), as they provide more control over dynamically sizing pictures (like the max and min values). Unfortunately, using these skips the creation of their webp counterpart.

It would be great if these could be covered by your webp extension as well.

**Comment by wazum** [comment]
I currently see no way to do that, there are no hooks, no events, nothing to know beforehand that the view helper is modifying the image.
They mess around with the images at a very low level (executing `convert` on the server) inside this extension:

https://github.com/FluidTYPO3/vhs/blob/c962d0dce84ad9b1cb2091ba716befab98be34ec/Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php#L133
