### ISSUE TITLE
Database update error

### ISSUE THREAD

**Issue by plojewski** [plan2net/webp#66]
Hi there,
after update from ^3.3 to ^4.1 I'm trying to Analyze Database Structure:

**ALTER TABLE "tx_webp_failed" ALTER "configuration_hash" TYPE VARCHAR(32) Current value: configuration_hash VARCHAR(40) DEFAULT NULL**

After that I've got an error:

Database update failed
Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32)

I use PostgreSQL 12.5 and PostgreSQL 13.1

**Comment by akiessling** [comment]
That happens on MySQL too since the field is now smaller due to https://github.com/plan2net/webp/commit/5aca9210e5e183e984b2ca4585ccbc3bbfed79a1#diff-63c8ca47fb6e2c18d65f7949fe8c05ca6c9108b1bf825b90803d1e0190c601eaL7
So we should probably just truncate the table?

**Comment by wazum** [comment]
Please simply truncate the table `tx_webp_failed`. I think that here the effort of a migration is not in relation to the benefit.
