### ISSUE TITLE
Problem / question concerning META-data

### ISSUE THREAD

**Issue by tohett** [plan2net/webp#67]
TYPO3 strips EXIF/IPCT/XMP-Data by default. I already changed that by setting "processor_stripColorProfileCommand" to "+profile '!iptc,!xmp,!exif,*'". Pictures created by TYPO3 (f.e. cropped images) keep now this data. However the WEBP that are created with your extension only have EXIF-Data (no XMP, no IPTC) and some information that were stored in the original file are lost (in my case "Copyright notice"), others are present. Is there something  I can do about it?
Thanks!

**Comment by wazum** [comment]
Currently you have to add the imagemagick configuration parameter yourself (again) in the extension configuration,
but I'll consider prepending `$GLOBALS['TYPO3_CONF_VARS']['GFX']['processor_stripColorProfileCommand']` to the parameter list.

**Comment by tohett** [comment]
Thanks for your answer; it would be great if your extension would respect the global parameters in the future :-)
