### ISSUE TITLE
consider safari on old osx and ios systems

### ISSUE THREAD

**Issue by subnoodle** [plan2net/webp#71]
Hi all,
some old osx and ios systems have safari browsers, which tell in the http header that webp would be an option to receive.
When they get an webp-image, they cannot display it, which leads to a broken image in the frontend.

So, i changed the block from:
```
#Integration of WEBP-Format with ext plan2net/webp\
RewriteCond %{HTTP_ACCEPT} image/webp
RewriteCond %{REQUEST_FILENAME} (.*)\.(png|gif|jpe?g)$
RewriteCond %{REQUEST_FILENAME}\.webp -f
RewriteRule ^ %{REQUEST_FILENAME}\.webp [L,T=image/webp]
```
to
```
#Integration of WEBP-Format with ext plan2net/webp\
RewriteCond %{HTTP_USER_AGENT} ^.*(Chrome|Firefox|Edge).*$ [NC]
RewriteCond %{HTTP_ACCEPT} image/webp
RewriteCond %{REQUEST_FILENAME} (.*)\.(png|gif|jpe?g)$
RewriteCond %{REQUEST_FILENAME}\.webp -f
RewriteRule ^ %{REQUEST_FILENAME}\.webp [L,T=image/webp]

```

Maybe this could be still improved, since it does not handle safari at all with webp.

See attached sceenshot for more version details. Didn't write it down earlier, so currently i don't know the exact osx / ios / safari versions.
![apple-webkit-webp](https://user-images.githubusercontent.com/9478590/191313146-b7d67479-85d2-4524-84ee-b18178129372.png)

**Comment by wazum** [comment]
Amended documentation in 5.0.0 (TYPO3 CMS 12)
