### ISSUE TITLE
Failed to convert image to webp: No options given for adapter

### ISSUE THREAD

**Issue by AffenJunge7** [plan2net/webp#74]
Hi there,
I got the extension installed on my Typo3 V10 instance and it is converting the images as desired.
Somehow I got errors on my frontend admin panel and checked the log files. It says the following:
 
`Fri, 04 Nov 2022 07:15:20 +0100 [ERROR] request="a4d65d0fc9c38" component="Plan2net.Webp.EventListener.AfterFileProcessing": Failed to convert image to webp: No options given for adapter "Plan2net\Webp\Converter\MagickConverter"! `

Do you have any idea?

This is my configuration:
![image](https://user-images.githubusercontent.com/32170053/199919002-96b7a264-b0de-4c1e-9a97-4c37ec0cbdb8.png)
image/jpeg::-quality 85 -define webp:lossless=false|image/png::-quality 75 -define webp:lossless=true|image/gif::-quality 85 -define webp:lossless=true

**Comment by mkarulin** [comment]
Same issue TYPO3 11.5 and plan2net/webp 4.1.2

**Comment by wazum** [comment]
I have added the elicited mime type to the log message in Commit #3123e6bb7bd14bef06b7ad09cce755df821aa8f8.

**Comment by wazum** [comment]
No reply, closed
