### ISSUE TITLE
Ausblenden der Webp Dateien in der Dateiliste

### ISSUE THREAD

**Issue by CarstenHager** [plan2net/webp#75]
Hallo Wolfgang, 

ich hoffe, es ist ok, wenn ich hier auf Deutsch schreibe. (Mein Englisch ist nicht so gut)

Folgendes "Problem".

Ich betreue eine Seite in der wir die Bilder im WebP Format zur Verfügung gestellt bekommen.
Wir haben die Bilder ins Backend hochgeladen, aber sie werden nicht angezeigt.

Im Code hab ich die Datei FileNameFilter.php gefunden, die alle webp Dateien rausfiltern.
Könnte man das über Konstanteneditor oder EXT Einstellungen einstellbar machen?

Gruß und danke für deine EXT
Carsten

**Comment by wazum** [comment]
Ja, wenn du die letzte Version benutzt, ist das dabei (hab noch kein Tag gemacht):
https://github.com/plan2net/webp/commit/f16b350f41cb2a4dc2ec858b0dba7ba35cff6d23

**Comment by CarstenHager** [comment]
Super, vielen dank!
