### ISSUE TITLE
Feature Request VIPS

### ISSUE THREAD

**Issue by M4rt1n17** [plan2net/webp#8]
As ImageMagick is producing a lot of serverload and takes a lot of time to produce all of these webp images I would love to see VIPS compatibility

This comparison was made back in 2016:
https://github.com/phzfi/RIC/wiki/Comparison-VIPS-vs-ImageMagick
It shows VIPS being 7 times faster then ImageMagick.

Here is another Test from late 2018 which is also including the amount of memory and time:
https://github.com/libvips/libvips/wiki/Speed-and-memory-use
https://github.com/libvips/libvips/wiki/Benchmarks

I would love to see a implementation of VIPS in Typo3 because its much faster then ImageMagick or GraphicsMagick

**Comment by wazum** [comment]
@M4rt1n17 what would you like to see in regards to the webp extension here?
This is imho a Core issue and would be better suited on forge.typo3.org as feature request.

**Comment by M4rt1n17** [comment]
Well indeed thats true. To have Typo3 Core support for VIPS would be much more awesome, but maybe this extension can support VIPS even if its not included/supported by the core?
Is there a chance to do so?

Somehow I cant register at forge.typo3.org dunno why. Is the regiostration at forge.typo3.org atm closed?
If so, could you kindly open a feature request ticket in my name?
Thanks.

**Comment by DanielRuf** [comment]
Hm, why not cwebp directly?

**Comment by wazum** [comment]
I think that different adapters for multiple libraries would be nice, I'll come back to this idea in the next weeks or months.

**Comment by M4rt1n17** [comment]
> Hm, why not cwebp directly?

This Feature Request aims not just on making this extension better but also the whole Typo3 Image Processing. cWebP is just for webp which fits perfectly in this extension but not in the whole Typo3 Core.

At least thats what I think.

But if cwebp is better then ImageMagick when it comes to webp would be nice tto have it supported here

**Comment by masi** [comment]
> This Feature Request aims not just on making this extension better but also the whole Typo3 Image
> Processing. cWebP is just for webp which fits perfectly in this extension but not in the whole Typo3
> Core.
I'm confused now. First you are argueing for a better image processing of TYPO3, which is definitely not the right place to do. Then you step back and ask for specific support of cWebP by this extension, whis is reasonable.

So what now?

PS: what better means for image processing depends on your needs: speed, quality of images, size of images, ... And of course also what you need to do. Only format conversion or transformations of any kind.

**Comment by M4rt1n17** [comment]
> > This Feature Request aims not just on making this extension better but also the whole Typo3 Image
> > Processing. cWebP is just for webp which fits perfectly in this extension but not in the whole Typo3
> > Core.
> > I'm confused now. First you are argueing for a better image processing of TYPO3, which is definitely not the right place to do. Then you step back and ask for specific support of cWebP by this extension, whis is reasonable.
> 
> So what now?
> 
> PS: what better means for image processing depends on your needs: speed, quality of images, size of images, ... And of course also what you need to do. Only format conversion or transformations of any kind.

1.) your wuote is wrong :) your quote includes party which I never wrote.
2.) dont get me wrong I would love to see this extension having cwebp support, but this ticket will be closed soon at this (my ticket) aims to a thing that is not related to this extension, becasue it is related to Typo3.
So becasue I like the the idea @DanielRuf has, I wanted him to create a new ticket for cwebp support.

3.) there are two things that Typo3 do
3.1) scaling/resizing/cropping
3.2) converting
4.) this extensions just covers the part of "3.2". Not the part of "3.1"
5.) my ticket (this ticket) aims to make "3.1" better but hit is not related to the extension its more up to Typo2 Core to improve "3.1". Thats why this ticket probably ( and also should) be closed!
6.) For not making this idea of cwebp getting destroid by closing this issue I just wanted to state that THIS ticket is sadly the wrong place to discuss this as it will be closed.

Dont get me wrong, I would love cwebp to be supported (and implemented into this extension.
But pls open a new ticket for...
Wait ...
I will do it for you :)

**Comment by DanielRuf** [comment]
Sorry, was at a meetup yesterday evening and my first workdays after my holiday are pretty full currently. Thanks for creating a new issue.

**Comment by wazum** [comment]
Heads-up: native libvips support landed in v14.4.0 via the new `VipsConverter` backend — pick *libvips (native)* in the converter dropdown. It runs in-process through jcupitt/vips + PHP's FFI extension (no shelling out to the CLI), so it's typically 2–3× faster than MagickConverter at equivalent quality and uses substantially less memory. Animated GIFs survive as animated WebP automatically.

Release notes: https://github.com/plan2net/webp/releases/tag/14.4.0
