### ISSUE TITLE
TYPO3 v12? 

### ISSUE THREAD

**Issue by Gitsko** [plan2net/webp#80]
Can you use the extension already for v12 or have basic things changed ?

**Comment by wazum** [comment]
@Gitsko  try `dev-master` and report if it works for you, then I'll release a new tag

**Comment by Gitsko** [comment]
Hi @wazum,

thanks for the fast answer, I install the extension but no webp variants are generated in fileadmin. 
I testet local with DDEV. My webserver supports webp with gm. I also remove the temporary assets.

**Comment by fritzdacat** [comment]
What are the plans for TYPO3 12?
Is there already a schedule when webp for TYPO3 12 will be available?

**Comment by wazum** [comment]
@fritzdacat `dev-master` is already compatible, please test and report

**Comment by JBlocks** [comment]
The new LTS v12.4 is released. Let's create a new release/tag for all projects outside and get rid of dev-master constraint in composer files. ;-)

**Comment by wazum** [comment]
Tagged new version 5.0.0
