### ISSUE TITLE
Add to README about "When convert PNG images to WEBP converted WEBPs are getting darker than original PNGs"

### ISSUE THREAD

**Issue by RostyslavMatviyiv** [plan2net/webp#82]
Hey hey! 

Weeks ago I've experienced an issue that I couldn't solve for a quite a long time. 

I've setup your extension and used same graphic library for convertion as used for the rest TYPO3 installation (ImageMagick). All worked good with jpegs but all PNGs converted to webp were much darker than original PNGs. Tried also "cwebp" itself, and then "ffmpeg" as well, and the results were same.

So issue was that on TYPO3 [GFX][processor_colorspace] option was set to RGB instead of sRGB, so when TYPO3 was resizing full scale sRGB images wrong colorspace was used which wasn't visible in browser for many years, however when then those resized PNGs were converted to WEBPs images were looking ugly. 

So I would kindly ask you to add some small note about colorprofile that is set in TYPO3 by [GFX][processor_colorspace]. 

For example - "if you experience that your webp images doesn't look the same as original ones (e.g. much darker) make sure you have correct profile set in [GFX][processor_colorspace]. Remember to Clean all _processed_ files after this change" or something similar...

It would definitely save me a lot of time, thanks in advance :)

And by the way this extension is amazing, Thank you a lot for sharing it :)

**Comment by wazum** [comment]
Amended documentation in 5.0.0 (TYPO3 CMS 12)
