### ISSUE TITLE
Class "Plan2net\Webp\Converter\AbstractConverter" not found

### ISSUE THREAD

**Issue by quadronet** [plan2net/webp#85]
With debug on this error is shown

Class "Plan2net\Webp\Converter\AbstractConverter" not found

PHP 8.1 TYPO3 11.5...

**Comment by wazum** [comment]
@quadronet 
I don't really know what I should do with this issue.
Maybe you can provide further details (type of installation, versions etc.) . Classes are loaded by composer autoloader.

**Comment by quadronet** [comment]
'version' => '4.2.0', TYPO3 is 11.5.19 . 
  No composer install. 
  The error is shown in Frontend with debug = 1
  Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'Plan2net\Webp\Converter\Exception\WillNotRetryWithConfigurationException' not found | Error thrown in file /var/www/vhosts/web/tester.de/typo3conf/ext/webp/Classes/Service/Webp.php in line 55

**Comment by wazum** [comment]
I'm sorry, I can't provide support for non-composer installations.
But here are some general hints: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Autoloading/Index.html#id2
