### ISSUE TITLE
Undefined array key "processor_stripColorProfileCommand"

### ISSUE THREAD

**Issue by brotkrueml** [plan2net/webp#92]
After the update to TYPO3 v12.4.11 the following error occurs:

```
ErrorException: Warning: Undefined array key "processor_stripColorProfileCommand"
  File "/vendor/plan2net/webp/Classes/Converter/MagickConverter.php", line 20, in Plan2net\Webp\Converter\MagickConverter::convert
    $parameters .= ' ' . $GLOBALS['TYPO3_CONF_VARS']['GFX']['processor_stripColorProfileCommand'];
```

This is due to the security issue TYPO3-CORE-SA-2024-002:
https://github.com/TYPO3/typo3/commit/6cc11761b8e2434fa4ccc9f096c65ca82569cfdf#diff-d7a98dbd38a8309e3c7f644a8c3708393e486f0c7a2fadc6151d9d5b6681548b

The `$GLOBALS['TYPO3_CONF_VARS']['GFX']['processor_stripColorProfileCommand']` is not defined anymore in the default configuration, instead the `$GLOBALS['TYPO3_CONF_VARS']['GFX']'processor_stripColorProfileParameters']` is now available.

**Comment by josefglatz** [comment]
_Also TYPO3 11.x is affected_

**Comment by tbal** [comment]
Can confirm:
plan2net/webp 4.2.0
TYPO3 11.5.36
