### ISSUE TITLE
PHP 8 Undefined array key

### ISSUE THREAD

**Issue by fritzdacat** [plan2net/webp#96]
In TYPO3 12 and PHP 8 (.2/.3), when using the webp extension, I consistently encounter this error in the logs:

Core: Error handler (FE): PHP Warning: Undefined array key "processor_stripColorProfileCommand" in /var/www/html/vendor/plan2net/webp/Classes/Converter/MagickConverter.php line 20

**Comment by fritzdacat** [comment]
Okay, I had "Use the system GFX 'processor_stripColorProfileCommand' setting for the MagickConverter converter" and didn't have "$GLOBALS['TYPO3_CONF_VARS']['GFX']['processor_stripColorProfileCommand'" set. Is it possible that $GLOBALS['TYPO3_CONF_VARS']['GFX']['processor_stripColorProfileCommand' is no longer set by default in TYPO3?

**Comment by garbast** [comment]
This still should not throw a warning and could easily be fixed with an ['processor_stripColorProfileCommand'] ?? false access.

**Comment by wazum** [comment]
Duplicate #92
